name: Actions Workflow 2

on:
  #push:
  #schedule:
    #- cron: "0/5 * * * *"
    #- cron: "0/6 * * * *"
    #- cron: "0 12 * * *"
    #- cron: "0 12 * FEB MON"
  #repository_dispatch:
    #types: [build]
  #pull_request:
    #types:
      #- closed
      #- assigned
      #- opened
      #- reopened
  push:
    branches:
      - main
      - 'feature/*' #matches feature/featurea, feature/x <- no cualquier string
      - 'feature/**' #matches feature/featurea, feature/x y feature/x/x <- cualquier string
      - '!feature/featC' # el ! se u sa para ignorar esa rama
    tags:
      - v1.*
    paths:
    - '**.js' 
    #branches-ignore:
      #- main
    #tags-ignore:
      #- ""
    #paths-ignore:
      #- 'docs/**'
  #pull_request:
    #branches:
      #- main
    
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.variable}}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: CarlosDavid
      - name: Log Grreting Time
        run: echo "${{ steps.greet.outputs.time }}"