name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        id: greet
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: CarlosDavid
      - name: Log Grreting Time
        run: echo "${{ steps.greet.outputs.time }}"