name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS 
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: | 
          cd react-app
          pwd
          ls
          npm i 
          npm run format_check
          npm test -- --coverage
        env: 
          CI: true